# Generated by Django 4.2.10 on 2024-02-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('merchandise_id', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock List',
                'db_table': 'stock',
            },
        ),
    ]
