# Generated by Django 4.2.10 on 2024-02-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0001_create_merchandise_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='user_id',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='username',
            field=models.CharField(default='admin', max_length=150),
            preserve_default=False,
        ),
    ]
