# Generated by Django 4.2.10 on 2024-02-12 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_change_soft_fk_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchandise.merchandise')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock List',
                'db_table': 'stock',
            },
        ),
    ]
