# Generated by Django 4.2.10 on 2024-02-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0004_change_foreign_key_field_to_one_to_one_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
