# Generated by Django 4.2.10 on 2024-02-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('merchandise_id', models.IntegerField()),
                ('merchandise_name', models.CharField(max_length=150)),
                ('merchandise_price', models.IntegerField()),
                ('merchandise_is_deleted', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Cart List',
                'db_table': 'cart',
            },
        ),
    ]
