# Generated by Django 4.2.10 on 2024-02-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_create_cart_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
