# Generated by Django 5.0.2 on 2024-02-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigIntegerField(unique=True)),
                ('activate_code', models.CharField(max_length=128, unique=True)),
                ('is_activated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Activate Mail',
                'verbose_name_plural': 'Activate Mail List',
                'db_table': 'activate_mail',
            },
        ),
    ]
