# Generated by Django 4.2 on 2024-02-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_update_user_active_mail_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivemail',
            old_name='activate_code',
            new_name='active_code',
        ),
    ]
