# Generated by Django 4.2 on 2024-02-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_edit_field_name_in_activate_mail_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivateMail',
            new_name='UserActiveMail',
        ),
        migrations.AlterModelOptions(
            name='useractivemail',
            options={'verbose_name': 'User Active Mail', 'verbose_name_plural': 'User Active Mail List'},
        ),
        migrations.AlterModelTable(
            name='useractivemail',
            table='user_active_mail',
        ),
    ]
